// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOmMInel-2R3zkT5BUGYzIXa6KpGhOk8w',
    appId: '1:359054847050:web:182803634f6cb3bf364ab3',
    messagingSenderId: '359054847050',
    projectId: 'smart-app-f8b7a',
    authDomain: 'smart-app-f8b7a.firebaseapp.com',
    storageBucket: 'smart-app-f8b7a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZNOUSkC7-oCb2eEcHEP9WQ7SzJ5z3nk0',
    appId: '1:359054847050:android:f011dc0b7ad85b65364ab3',
    messagingSenderId: '359054847050',
    projectId: 'smart-app-f8b7a',
    storageBucket: 'smart-app-f8b7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA88viJn087SNjiVrM2DsGBIGI5Kh3hh4w',
    appId: '1:359054847050:ios:fef3620b7ea15529364ab3',
    messagingSenderId: '359054847050',
    projectId: 'smart-app-f8b7a',
    storageBucket: 'smart-app-f8b7a.firebasestorage.app',
    iosBundleId: 'com.projectf.fruitsClassifier',
  );
}
